### ISSUE TITLE
Load file button not showing json files in my computer

### ISSUE THREAD

**Issue by bsde1234** [adar2/Facebook-Posts-Automation#2]
After clicking load file button and browse to my folder containing json files it doesn't show json files. 

What is the time delay for json file between each post?

**Comment by adar2** [comment]
> After clicking load file button and browse to my folder containing JSON files it doesn't show JSON files.

Please try again, and let me know if you still encounter this problem.

> What is the time delay for JSON file between each post?

In case you are using tasks , the delay will be around 15 secs, if you're planning on posting manually,it will depend on you're internet connection as the bot will post them one after the other.

**Comment by bsde1234** [comment]
I get error when loading like `list indices must be intigers or slices not str`. My json looks like, 
```
[
    {
        "posts": [
            {
                "msg": "Some texts"
            }
        ],
        "targets": [
            {
                "target": "https://www.facebook.com/groups/189076xxxx"
            }
        ]
    },
    {
        "posts": [
            {
                "msg": "Some texts"
            }
        ],
        "targets": [
            {
                "target": "https://www.facebook.com/groups/189076xxxx"
            }
        ]
    },
    {
        "posts": [
            {
                "msg": "some texts"
            }
        ],
        "targets": [
            {
                "target": "https://www.facebook.com/groups/189076xxxx"
            }
        ]
    }
]

**Comment by adar2** [comment]
> I get error when loading like `list indices must be intigers or slices not str`. My json looks like,


Please note that posts and targets are independent from each other, therefore your json should look like,




```

{
    "posts":[
                {"msg":"sometext1" ,"media":""},
                {"msg":"sometext2", "media":"C:\\some_media_path"}
            ],
    "targets":[
                {"target": "https://www.facebook.com/groups/189076xxxx"},
                {"target": "https://www.facebook.com/groups/189076xxxx"}
              ]
}

```

**Comment by bsde1234** [comment]
Now I get duplicate post, aborting ... message. Do I need to add owner id and if yes what is that?

**Comment by adar2** [comment]
> Now I get duplicate post, aborting ... message. Do I need to add owner id and if yes what is that?

Do the post you are trying to load already exists for that current user?

No, you do not need the owner id.

If you are trying to load posts and targets for multiple users , you will have to do it per user.

**Comment by bsde1234** [comment]
Yes some posts are duplicate, but that are required..

**Comment by adar2** [comment]
Can you please explain what are you trying to do?
Why do you wish to have duplicate posts?

**Comment by bsde1234** [comment]
It may be a very custom need, I am trying to post government exam question and answers which have same answer for different questions(anawer only is a post). If you dont want to change your code post a specific edit here.

**Comment by adar2** [comment]
If you insists on continuing with this approach you may want to edit the DataBaseWrapper.py under the Modules directory, and edit some of the posts methods or all of them.
I would recommend to try and find alternative approach as have multiple identical posts under the same user may be ambiguous, 
and may cause some things not to work.

**Comment by bsde1234** [comment]
Even if json contain unique posts I get deplicate target aborting message. So if the target is same I need to add only once in json file? After I create task it post first message only. Do i need to select all message when creating task name? I tried that but it wont select. I get following in console 
```
020-11-30 14:09:15,366 - Duplicate target , aborting..
qt.xkb.compose: failed to create compose table
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1586, resource id: 28262222, major code: 40 (TranslateCoords), minor code: 0
2020-11-30 14:13:32,801 - Duplicate target , aborting..
Posted to :http://mbasic.facebook.com/groups/189076xxx
```

**Comment by adar2** [comment]
> So if the target is same I need to add only once in json file? 

Yes, in general once you have added post/target, it will remain in the database until you delete it or the user associated with it,
therefore you will need to do all this preparation only  once.

> Do i need to select all message when creating task name? I tried that but it wont select.

"Tasks are comprised of post, one or more targets,date and task name."

You will have to create multiple tasks.

**Comment by bsde1234** [comment]
Do I need to create task for each post? if yes can I do it in json or any easy way?

**Comment by adar2** [comment]
> Do I need to create task for each post? if yes can I do it in json or any easy way?

Yes, and currently no, but sometime in the near future .
