### ISSUE TITLE
I need to post more than one image for post 

### ISSUE THREAD

**Issue by Mat5heus** [adar2/Facebook-Posts-Automation#3]
There are some way to post more than one picture at time? I have many picture here and some of them needed to be scheduled and posted together...

**Comment by adar2** [comment]
> 
> 
> There are some way to post more than one picture at time? 

Unfortunately no.  
You're welcome to fork this project to add this feature and make a pull request.

**Comment by Mat5heus** [comment]
Ok, I will try something here. Thanks!
