### ISSUE TITLE
Posts/Targets import not working

### ISSUE THREAD

**Issue by 63rrit** [adar2/Facebook-Posts-Automation#4]
Trying to use the .json import is crashing the gui.

**Comment by adar2** [comment]
> Trying to use the .json import is crashing the gui.

Post your JSON file content here

**Comment by 63rrit** [comment]
[postgroupfile.txt](https://github.com/adar2/Facebook-Posts-Automation/files/7244837/postgroupfile.txt)

**Comment by adar2** [comment]
tried that looks fine.
can you please attach stacktrace of the crash
